#pragma once

#include QMK_KEYBOARD_H
#include "common.h"

// #define NUM_ENCODERS 2
#define NUM_DIRECTIONS 2

const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [_QWERTY] = { ENCODER_CCW_CW(S(KC_TAB), KC_TAB), ENCODER_CCW_CW(KC_WH_U, KC_WH_D) },
    [_DEFAULTS] = { ENCODER_CCW_CW(S(KC_TAB), KC_TAB), ENCODER_CCW_CW(KC_WH_U, KC_WH_D) },
    [_GAMING] = { ENCODER_CCW_CW(S(KC_TAB), KC_TAB), ENCODER_CCW_CW(KC_WH_U, KC_WH_D) },
    [_LOWER] = { ENCODER_CCW_CW(S(KC_TAB), KC_TAB), ENCODER_CCW_CW(KC_WH_U, KC_WH_D) },
    [_RAISE] = { ENCODER_CCW_CW(C(S(KC_TAB)), C(KC_TAB)), ENCODER_CCW_CW(KC_WH_U, KC_WH_D) },
    [_ADJUST] = { ENCODER_CCW_CW(S(KC_TAB), KC_TAB), ENCODER_CCW_CW(KC_WH_U, KC_WH_D) },
};
