#pragma once

#include QMK_KEYBOARD_H
#include "common.h"

// #define NUM_ENCODERS 2
#define NUM_DIRECTIONS 2
#define ENCODER_CONFIG { ENCODER_CCW_CW(S(KC_TAB), KC_TAB), ENCODER_CCW_CW(KC_WH_U, KC_WH_D) }
#define ENCODER_INVERSE_CONFIG { ENCODER_CCW_CW(C(S(KC_TAB)), C(KC_TAB)), ENCODER_CCW_CW(KC_WH_U, KC_WH_D) }

const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [_QWERTY] = ENCODER_CONFIG,
    [_GAMING] = ENCODER_CONFIG,
    [_LOWER] = ENCODER_CONFIG,
    [_RAISE] = ENCODER_INVERSE_CONFIG,
    [_ADJUST] = ENCODER_CONFIG,
};
